"""Add nationality field to pupils table

Revision ID: 678d78fe63b9
Revises: b97ff66f885d
Create Date: 2025-12-28 12:58:49.783480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678d78fe63b9'
down_revision = 'b97ff66f885d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pupils', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
