"""Add days column to Term model

Revision ID: 7abbbe032026
Revises: e9f9d641d9aa
Create Date: 2025-12-24 16:27:20.773844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abbbe032026'
down_revision = 'e9f9d641d9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_column('days')

    # ### end Alembic commands ###
