"""Add notification model

Revision ID: 82acab2f4cc5
Revises: 7abbbe032026
Create Date: 2025-12-24 18:49:16.052881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82acab2f4cc5'
down_revision = '7abbbe032026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['system_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
